"use client"

import { useState, useRef } from "react"
import { createClient } from "@/lib/supabase/client"

interface ContentSection { heading: string; content: string }
interface ContentData {
  lessonTitle: string
  introduction: string
  sections: ContentSection[]
  bulletSummary: string[]
  actionSteps: string[]
  callToAction: string
}

function PdfExportButton({ content, lessonTitle }: { content: ContentData; lessonTitle: string }) {
  const [exporting, setExporting] = useState(false)

  async function exportPdf() {
    setExporting(true)
    try {
      const printWindow = window.open("", "_blank")
      if (!printWindow) return

      const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${content.lessonTitle}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Georgia', serif; font-size: 11pt; line-height: 1.7; color: #1a1a2e; background: #fff; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { border-bottom: 3px solid #00d4ff; padding-bottom: 20px; margin-bottom: 30px; }
    .brand { font-size: 10pt; font-weight: 700; color: #00d4ff; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 8px; font-family: sans-serif; }
    h1 { font-size: 22pt; font-weight: 700; color: #0a0a1a; line-height: 1.3; margin-bottom: 8px; }
    .intro { font-size: 11pt; color: #444; line-height: 1.8; margin-bottom: 30px; padding: 16px 20px; background: #f8f9ff; border-left: 4px solid #00d4ff; border-radius: 0 6px 6px 0; }
    h2 { font-size: 14pt; font-weight: 700; color: #0a0a1a; margin: 28px 0 10px; font-family: sans-serif; }
    p { margin-bottom: 14px; color: #333; }
    .summary-box { background: #f0feff; border: 1px solid #b0eeff; border-radius: 8px; padding: 20px 24px; margin: 30px 0; }
    .summary-box h2 { color: #007a99; margin-top: 0; }
    .summary-box li { list-style: none; padding: 5px 0; color: #1a1a2e; }
    .summary-box li::before { content: "✓ "; color: #00d4ff; font-weight: bold; }
    .actions-box { background: #fff8f0; border: 1px solid #ffd4a0; border-radius: 8px; padding: 20px 24px; margin: 20px 0; }
    .actions-box h2 { color: #994400; margin-top: 0; }
    .actions-box li { list-style: none; padding: 5px 0; counter-increment: action; }
    .actions-box li::before { content: counter(action) ". "; color: #ff8c00; font-weight: bold; }
    .actions-list { counter-reset: action; }
    .cta-box { background: #0a0a1a; color: #fff; border-radius: 8px; padding: 20px 24px; margin: 20px 0; text-align: center; }
    .cta-box p { color: #e0e0f0; font-size: 12pt; margin: 0; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee; font-size: 9pt; color: #999; font-family: sans-serif; display: flex; justify-content: space-between; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">Nixio — Content Studio</div>
    <h1>${content.lessonTitle}</h1>
  </div>
  <div class="intro">${content.introduction}</div>
  ${content.sections?.map(s => `<h2>${s.heading}</h2><p>${s.content.replace(/\n/g, "</p><p>")}</p>`).join("")}
  <div class="summary-box">
    <h2>Key Takeaways</h2>
    <ul>${content.bulletSummary?.map(b => `<li>${b}</li>`).join("")}</ul>
  </div>
  <div class="actions-box">
    <h2>Your Action Steps</h2>
    <ol class="actions-list">${content.actionSteps?.map(a => `<li>${a}</li>`).join("")}</ol>
  </div>
  <div class="cta-box"><p>${content.callToAction}</p></div>
  <div class="footer">
    <span>Generated by Nixio</span>
    <span>${new Date().toLocaleDateString()}</span>
  </div>
  <script>window.onload = () => { window.print(); }</script>
</body>
</html>`
      printWindow.document.write(html)
      printWindow.document.close()
    } finally {
      setExporting(false)
    }
  }

  return (
    <button
      onClick={exportPdf}
      disabled={exporting}
      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-destructive/80 hover:bg-destructive text-white text-sm font-semibold transition-colors"
    >
      <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
        <path d="M2 10v2a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-2M7 1v7M4.5 5.5L7 8l2.5-2.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
      </svg>
      {exporting ? "Preparing..." : "Export PDF"}
    </button>
  )
}

export default function ContentPage() {
  const [lessonTitle, setLessonTitle] = useState("")
  const [moduleName, setModuleName] = useState("")
  const [targetAudience, setTargetAudience] = useState("")
  const [loading, setLoading] = useState(false)
  const [content, setContent] = useState<ContentData | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)

  async function generate(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setError(null)
    setContent(null)
    setSaved(false)

    const prompt = `Lesson title: ${lessonTitle}\nModule: ${moduleName}\nTarget audience: ${targetAudience}\n\nWrite a complete, engaging lesson with all sections.`

    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ type: "content", prompt }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      const jsonMatch = data.result.match(/\{[\s\S]*\}/)
      if (jsonMatch) setContent(JSON.parse(jsonMatch[0]))
      else throw new Error("Could not parse content")
    } catch (err: any) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  async function saveContent() {
    if (!content) return
    setSaving(true)
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return
    await supabase.from("contents").insert({
      user_id: user.id,
      module_name: moduleName,
      lesson_name: lessonTitle,
      full_content: content.sections?.map(s => `## ${s.heading}\n${s.content}`).join("\n\n"),
      bullet_summaries: content.bulletSummary,
      action_steps: content.actionSteps,
    })
    setSaved(true)
    setSaving(false)
  }

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6 animate-fade-in">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Content Studio</h1>
        <p className="text-muted-foreground text-sm mt-1">Generate full lesson scripts and export them as professional PDFs.</p>
      </div>

      <form onSubmit={generate} className="p-5 rounded-xl bg-card border border-border space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Lesson title</label>
            <input value={lessonTitle} onChange={e => setLessonTitle(e.target.value)} required placeholder="e.g. How to write a cold email that converts" className="w-full px-3 py-2.5 rounded-lg bg-secondary border border-border text-foreground placeholder:text-muted-foreground text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-colors"/>
          </div>
          <div className="space-y-1.5">
            <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Module name</label>
            <input value={moduleName} onChange={e => setModuleName(e.target.value)} required placeholder="e.g. Module 2: Client Acquisition" className="w-full px-3 py-2.5 rounded-lg bg-secondary border border-border text-foreground placeholder:text-muted-foreground text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-colors"/>
          </div>
        </div>
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">Target audience</label>
          <input value={targetAudience} onChange={e => setTargetAudience(e.target.value)} required placeholder="e.g. Freelancers looking for their first client" className="w-full px-3 py-2.5 rounded-lg bg-secondary border border-border text-foreground placeholder:text-muted-foreground text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary transition-colors"/>
        </div>
        {error && <div className="p-3 rounded-lg bg-destructive/10 border border-destructive/20 text-destructive text-xs">{error}</div>}
        <button type="submit" disabled={loading} className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-primary text-primary-foreground text-sm font-bold hover:opacity-90 disabled:opacity-50 transition-opacity">
          {loading ? <><span className="w-3.5 h-3.5 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />Writing lesson...</> : <><svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M7 1l1.5 3.5L12 6 8.5 7.5 7 11 5.5 7.5 2 6l3.5-1.5L7 1Z" fill="currentColor"/></svg>Generate full lesson</>}
        </button>
      </form>

      {content && (
        <div className="space-y-5 animate-fade-in">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-bold text-foreground">{content.lessonTitle}</h2>
            <div className="flex items-center gap-2">
              <button onClick={saveContent} disabled={saving || saved} className="px-3 py-1.5 rounded-lg bg-primary/10 text-primary border border-primary/20 text-xs font-semibold hover:bg-primary/15 disabled:opacity-50 transition-colors">
                {saved ? "Saved!" : saving ? "Saving..." : "Save"}
              </button>
              <PdfExportButton content={content} lessonTitle={content.lessonTitle} />
            </div>
          </div>

          <div className="p-4 rounded-xl bg-primary/5 border border-primary/15">
            <p className="text-sm text-foreground leading-relaxed">{content.introduction}</p>
          </div>

          {content.sections?.map((section, i) => (
            <div key={i} className="p-5 rounded-xl bg-card border border-border">
              <h3 className="text-sm font-bold text-foreground mb-3">{section.heading}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">{section.content}</p>
            </div>
          ))}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-card border border-border">
              <h3 className="text-xs font-semibold text-primary uppercase tracking-wide mb-3">Key Takeaways</h3>
              <ul className="space-y-2">
                {content.bulletSummary?.map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-foreground">
                    <svg width="12" height="12" viewBox="0 0 12 12" fill="none" className="shrink-0 mt-0.5 text-primary">
                      <path d="M1.5 6.5l3 3 6-7" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                    {item}
                  </li>
                ))}
              </ul>
            </div>

            <div className="p-4 rounded-xl bg-card border border-border">
              <h3 className="text-xs font-semibold text-accent uppercase tracking-wide mb-3">Action Steps</h3>
              <ol className="space-y-2">
                {content.actionSteps?.map((step, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-foreground">
                    <span className="shrink-0 w-4 h-4 rounded-full bg-accent/15 text-accent flex items-center justify-center text-[10px] font-bold mt-0.5">{i + 1}</span>
                    {step}
                  </li>
                ))}
              </ol>
            </div>
          </div>

          <div className="p-4 rounded-xl bg-secondary border border-border text-center">
            <p className="text-sm text-foreground font-medium">{content.callToAction}</p>
          </div>
        </div>
      )}
    </div>
  )
}
