import { createClient } from "@supabase/supabase-js"
import { NextResponse } from "next/server"

// Use a plain Supabase client — no cookie session needed (public endpoint)
function getSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
}

export async function POST(req: Request) {
  try {
    const body = await req.json()
    const { name, email, subject, category, message } = body

    if (!name || !email || !subject || !message) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    const supabase = getSupabase()

    // Insert ticket — ticket_number is auto-generated by DB trigger
    const { data: ticket, error: ticketError } = await supabase
      .from("support_tickets")
      .insert({ name, email, subject, category: category || "general" })
      .select("id, ticket_number")
      .single()

    if (ticketError || !ticket) {
      console.error("[v0] ticket insert error:", ticketError)
      return NextResponse.json({ error: ticketError?.message || "Failed to create ticket" }, { status: 500 })
    }

    // Insert opening message
    const { error: msgError } = await supabase
      .from("ticket_messages")
      .insert({
        ticket_id: ticket.id,
        sender_type: "user",
        sender_name: name,
        body: message,
      })

    if (msgError) {
      console.error("[v0] message insert error:", msgError)
      return NextResponse.json({ error: msgError.message }, { status: 500 })
    }

    return NextResponse.json({ ticketNumber: ticket.ticket_number, ticketId: ticket.id })
  } catch (e) {
    console.error("[v0] tickets route error:", e)
    return NextResponse.json({ error: "Server error" }, { status: 500 })
  }
}

// Lookup a ticket by number + email (for tracker)
export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url)
    const ticketNumber = searchParams.get("ticket_number")
    const email = searchParams.get("email")

    if (!ticketNumber || !email) {
      return NextResponse.json({ error: "ticket_number and email are required" }, { status: 400 })
    }

    const supabase = getSupabase()

    const { data: ticket, error } = await supabase
      .from("support_tickets")
      .select("id, ticket_number, name, email, subject, category, status, created_at")
      .eq("ticket_number", ticketNumber.toUpperCase().trim())
      .eq("email", email.toLowerCase().trim())
      .single()

    if (error || !ticket) {
      return NextResponse.json({ error: "Ticket not found. Check your ticket number and email." }, { status: 404 })
    }

    return NextResponse.json({ ticket })
  } catch (e) {
    console.error("[v0] tickets GET error:", e)
    return NextResponse.json({ error: "Server error" }, { status: 500 })
  }
}
