import type { Metadata } from "next"
import { PolicyLayout } from "@/components/nixio/policy-layout"

export const metadata: Metadata = {
  title: "Terms of Service — Nixio",
  description: "The terms and conditions governing your use of Nixio.",
}

const SECTIONS = [
  {
    heading: "Acceptance of Terms",
    body: "By creating an account or accessing Nixio, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree with any part of these terms, you must not use the platform. These terms apply to all users, including free trial users and paid subscribers.",
  },
  {
    heading: "Description of Service",
    body: "Nixio is an AI-powered platform that helps solopreneurs and digital product creators validate ideas, architect products, generate content, build marketing funnels, and create exportable PDF documents. The service is provided on an 'as is' and 'as available' basis. Features may change at any time as we continue to develop the product.",
  },
  {
    heading: "Account Registration",
    body: [
      "You must provide accurate and complete information when creating your account.",
      "You are responsible for maintaining the confidentiality of your login credentials.",
      "You must notify us immediately at hello@nixio.app if you suspect unauthorised access.",
      "One account per person. You may not share or transfer your account to another individual.",
      "You must be at least 16 years old to use Nixio.",
    ],
  },
  {
    heading: "Subscriptions & Billing",
    body: [
      "Nixio offers a Starter plan ($19.99/month, 10 AI generations) and a Pro plan ($49.99/month, unlimited).",
      "Both plans include a 3-day free trial. No credit card is required to start the trial.",
      "Subscriptions are billed monthly in advance. Payments are processed securely by Polar.sh.",
      "You may cancel your subscription at any time from Settings. Cancellation takes effect at the end of the current billing period.",
      "We reserve the right to change pricing with 30 days' notice. Existing subscribers will be grandfathered at their current rate for one billing cycle.",
    ],
  },
  {
    heading: "Acceptable Use",
    body: [
      "You may not use Nixio to generate spam, misleading content, or material that violates any applicable law.",
      "You may not attempt to reverse-engineer, scrape, or extract the AI models or platform code.",
      "You may not use the platform for any activity that violates the intellectual property rights of others.",
      "You may not share your account or resell access to Nixio without our written consent.",
      "We reserve the right to suspend accounts that violate these terms without prior notice.",
    ],
  },
  {
    heading: "Intellectual Property",
    body: "You retain full ownership of any content, blueprints, and documents you create using Nixio. By using the service, you grant Nixio a limited licence to process and store your content solely to provide the service. The Nixio platform, branding, AI prompts, and underlying technology remain the intellectual property of Nixio.",
  },
  {
    heading: "AI-Generated Content",
    body: "Content generated by Nixio's AI tools is provided for informational and creative purposes only. It does not constitute legal, financial, or professional advice. The quality and accuracy of AI outputs may vary. You are responsible for reviewing, editing, and verifying any content before publishing or distributing it.",
  },
  {
    heading: "Limitation of Liability",
    body: "To the maximum extent permitted by law, Nixio shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform. Our total cumulative liability to you shall not exceed the amount you paid to Nixio in the three months preceding the claim.",
  },
  {
    heading: "Service Availability",
    body: "We aim for 99.9% uptime but do not guarantee uninterrupted access. Planned maintenance will be announced with advance notice. We are not liable for any losses resulting from downtime or service interruptions outside our reasonable control.",
  },
  {
    heading: "Termination",
    body: "You may terminate your account at any time from the Settings page. We may terminate or suspend your account if you breach these Terms. Upon termination, your access to the platform will cease and your data will be deleted in accordance with our Privacy Policy.",
  },
  {
    heading: "Governing Law",
    body: "These Terms are governed by and construed in accordance with applicable law. Any disputes arising from these terms shall be resolved through good-faith negotiation first, then binding arbitration if necessary. Nothing in these Terms limits your statutory consumer rights.",
  },
  {
    heading: "Changes to Terms",
    body: "We may update these Terms at any time. Material changes will be communicated via email or an in-app notification with at least 14 days' notice before they take effect. Continued use of Nixio after the effective date constitutes acceptance of the updated Terms.",
  },
]

export default function TermsPage() {
  return (
    <PolicyLayout
      title="Terms of Service"
      subtitle="These terms govern your use of Nixio. Please read them carefully before using the platform."
      lastUpdated="April 28, 2026"
      badge="Legal"
      badgeColor="#059669"
      sections={SECTIONS}
    />
  )
}
